### PR TITLE
Update .Net Core SDK from 2.1.400 to 2.2.401

### PR DESCRIPTION
**Pull request by bergmeister**

### CODE REVIEW

**Comment by felixfbecker** [comment]
Does this have any advantages or disadvantages? E.g. could it break compatibility with older PowerShell Core versions?

**Comment by bergmeister** [comment]
This just so that the built .Net binaries were built using the latest patched version of msbuild as there are usually security related fixed in SDK updates, in the meantime the latest LTS version is already 2.1.801
https://dotnet.microsoft.com/download/dotnet-core/2.1
Since we use .Net Standard now, we could even use the 2.2 SDK now. This does not affect PS at all, what matters is the runtime target in the csproj (which is now `netstandard2.0`, on which any version of PSCore can run, even 7.0)

**Comment by felixfbecker** [comment]
I'd be down for 2.2, wanna do that?

**Comment by bergmeister** [comment]
yes, we can definitely try that. Let's see if travis supports it. Technically we could already go for 3.0-preview because, which is already supported for production but will be released anyway in a month at .net conf

**Comment by bergmeister** [comment]
Ok, it seems this travis environment does not support 2.2 well. I suggest to update `trusty` to `xenial` (i.e. Ubuntu 14 to 16). Mainstream support for Ubuntu 14 has already ended and PowerShell is not supporting it any more. I'd say that is another PR though...

**Comment by felixfbecker** [comment]
Already switched to xenial in #38

**Comment by felixfbecker** [comment]
Pushed to master

**Comment by bergmeister** [comment]
Ok, thanks, it worked now :-)

**Pull request merged**
