### PR TITLE
Target .Net Standard 2.0

### PR DESCRIPTION
**Pull request by bergmeister**
API's are nearly the same in terms of behaviour, the only lost functionality to cancel the async reading of the file.
This also highly reduced the size of the module from around 160 MB to 10MB
In practice one could even look at it in detail and exclude most DLLs (as PowerShell provides most of them therefore only DLLs from the project itself and it's NuGet packages are technically needed.

### CODE REVIEW

**Comment by bergmeister** [comment]
Thanks. No, there shouldn't be anything left to do. I created it only as draft because I thought you might want me to make some changes after first review.

**Comment by felixfbecker** [comment]
Thanks, awesome size reduction!

**Comment by felixfbecker** [comment]
Hmm, it seems like newer versions of the PowerShell SDK are not compatible with .netstandard but only .netcore? https://travis-ci.org/felixfbecker/PSKubectl/builds/567063841#L745

**Comment by bergmeister** [comment]
I would not update the PS SDK until 6.1 is deprecated. You don't need to reference 6.2 for it to work on 6.2. One would only need to reference it if you use APIs that are only available in newer versions. I can take a look at the issue briefly but I think you might be able to dump the SDK and replace it with SMA but I cannot say that for sure until I've looked at what APIs you use

**Comment by felixfbecker** [comment]
Ah, makes sense.
What's SMA?

**Comment by bergmeister** [comment]
System.Management.Automation
This is just a reference library (a bit like a header file as a C++ analogy) so that you know which APIs PowerShell exposes, one needs the PS SDK only if you wanted to e.g. host PowerShell yourself but this is not needed for a cmdlet because PowerShell already hosts you as a guest.
It works on my branch already but the module building logic would need to be tweaked to avoid publishing the whole runtime again similar to how it was before we improved it to use netstandard,  unfortunately NuGet has a big which makes dotnet build not work to just get the necessary dlls because all we need is your kubectl dll and the ones from the nuget packages except the PowerShell onew because the PowerShell runtime already has them

**Comment by felixfbecker** [comment]
Would it help to add some commands to build.ps1? E.g. delete unneeded DLLs

**Comment by bergmeister** [comment]
Usually one just takes the output from `dotnet build` but due to [this](https://github.com/NuGet/Home/issues/4488) Nuget issue, we don't get the DLLs from the other NuGet packages. Deleting is not straightforward (e.g. just deleting System.* and Microsoft.* also removes some required DLLs  such as e.g. `Microsoft.Extensions.Logging.Abstractions`). With different .Net SDKs, the list of files to be deleted will change over time, therefore the approach is usually to whitelist but this comes with the drawback of having to maintain/update that list if one updates e.g. NuGet packages and in a newer version, they added a new DLL for example...

**Comment by felixfbecker** [comment]
Hmm I don't know if it's worth the maintenance burden. Is module size really a concern?

**Comment by bergmeister** [comment]
module size means slower installation and generally just lots of space that accumulates. We optimised already 90MB away with the .Net Standard2.0 tweak, so one could argue that we should follow the 80-20 rule and stop here since the additional improvement of is much smaller now. I'll try to see if there is a way using `dotnet build` by avoiding the Nuget bug because then there would not be the maintenance burden...

**Pull request merged**
